# To test, concurrently
#   pnpm build && pnpm preview --host 0.0.0.0
#	  lychee dist src/content

base = "http://127.0.0.1:4321"
remap = [ "https://labs.leaningtech.com http://127.0.0.1:4321" ]

scheme = [ "http", "https" ]

# Don't check links inside `<code>` and `<pre>` blocks
include_verbatim = false

exclude = [
	'.*(twitter|github|linkedin|reddit|youtube|youtube-nocookie)\.com.*',
	'.*packages\.ubuntu\.com.*',
	'http://127\.0\.0\.1:(8000|8080|8086).*',
	'.*rpm\.leaningtech\.com.*',
	'.*mydomain\.com.*',
	'.*microsoft\.com.*',
	'.*medium\.com.*',
	'file://.*',
	'chrome://.*',
	'wss?://*',
	'http://localhost:8080/',
	'https://swingset3.dev.java.net/',
	'https://raw.githubusercontent.com/leaningtech/cheerpj-example-applet/main',
	'https://raw.githubusercontent.com/leaningtech/cheerpj-example-swingset3/main',
	'https://raw.githubusercontent.com/leaningtech/cheerpj-meta/main/examples/SwingSet3/',
	'https://raw.githubusercontent.com/leaningtech/cheerpj-meta/main/examples/Pitch-Applet/',
	'https://web.archive.org/web/20110204185537/http://jdk6.java.net/plugin2/liveconnect/#JS_JAVA_CONVERSIONS',
	'https://swingset3.dev.java.net/',
	'https://my.url.com/',
	'https://www.w3.org/.*',
	'https://lkml.org/.*',
	'https://www.wireguard.com/',
	'http://127.0.0.1:8081/client.html',
	'https://chrome.google.com/webstore/.*',
	'https://stackoverflow.com/questions/ask.*', # 403
	'.*\.ext2'	
]

max_concurrency = 14
